/* A second pop-science trivia set, animal-themed. Kept local for the same
   reasons as facts.js — no network dependency, works offline. */

window.ANIMAL_FACTS = [
  "A shrimp's heart is located in its head.",
  "Elephants are the only mammals that can't jump.",
  "A snail can sleep for up to three years at a stretch.",
  "Giraffes get by on as little as 5 to 30 minutes of sleep in a 24-hour period.",
  "A group of jellyfish is called a smack.",
  "Axolotls can regenerate not just limbs, but parts of their brain, spinal cord, and heart.",
  "Pigeons can be trained to tell the difference between letters of the alphabet.",
  "A tiger's skin is striped just like its fur — no two tigers share the same pattern.",
  "Rats emit ultrasonic 'laughter' when they're tickled.",
  "The mantis shrimp can throw a punch that accelerates faster than a bullet leaving a gun.",
  "A single beehive can house up to 60,000 bees.",
  "Cows have nearly 360-degree panoramic vision.",
  "Sloths can hold their breath for up to about 40 minutes, longer than dolphins can.",
  "Kangaroos are physically unable to walk backwards.",
  "A diving blue whale's heart can slow to just two beats a minute.",
  "Chickens are the closest living relatives of the Tyrannosaurus rex.",
  "Some frogs can freeze solid over winter and thaw out alive again in spring.",
  "A group of rhinos is called a crash.",
  "An ostrich's eyeball is bigger than its brain.",
  "A dog's sense of smell is estimated to be tens of thousands of times more sensitive than a human's.",
  "Horses can sleep both lying down and standing up.",
  "A cheetah can go from 0 to 60 mph in about three seconds.",
  "The blue-ringed octopus, despite being about the size of a golf ball, carries enough venom to kill an adult human within minutes.",
  "Male seahorses, not females, carry and give birth to the babies.",
  "A woodpecker can peck a tree up to 20 times a second.",
  "Polar bears have black skin hidden underneath their white fur.",
  "The world's oldest known living land animal is a tortoise named Jonathan, who is over 190 years old.",
  "Bats are the only mammals capable of sustained, powered flight.",
  "A group of porcupines is called a prickle.",
  "Camels store fat, not water, in their humps.",
  "Ravens have been observed making and using tools to solve problems.",
  "A hippo's skin secretes a natural reddish substance that acts like sunscreen.",
  "An anteater can flick its tongue up to 150 times a minute.",
  "Goats have rectangular pupils, giving them a wide field of view to spot predators.",
  "A group of lions is called a pride.",
  "Some species of turtles can absorb oxygen through their rear end, effectively 'breathing' through it.",
  "The Greenland shark can live for more than 300 years, making it the longest-living vertebrate known.",
  "Elephants can detect distant rainfall and will migrate toward it from many kilometres away.",
  "A cat's purr vibrates at a frequency that may help promote healing in bone and tissue.",
  "Pigs are considered one of the most intelligent domesticated animals, outperforming dogs in some cognitive tests.",
  "A group of hedgehogs is called an array.",
  "Bees can learn to recognise individual human faces.",
  "A giraffe's tongue can be up to 50 centimetres long and is often dark bluish-purple to help prevent sunburn.",
  "Some ants can lift objects up to 50 times their own body weight.",
  "Over long distances, the pronghorn antelope can outrun almost any predator, including the cheetah, thanks to its stamina.",
  "A group of frogs is called an army.",
  "The platypus is one of the very few mammals that lay eggs instead of giving birth to live young.",
  "Squirrels inadvertently plant thousands of new trees each year by forgetting where they buried their acorns.",
  "Male emperor penguins incubate their single egg for around two months without eating.",
  "A wolf's howl can be heard by other wolves up to 10 kilometres away in open terrain.",
  "The Arctic tern makes the longest migration of any animal, flying pole to pole and back — nearly 70,000 kilometres a year.",
  "A group of otters is called a romp.",
  "Some lizards can detach and later regrow their own tails to escape predators.",
  "Koalas sleep up to 20 hours a day, partly because their eucalyptus-only diet is so low in nutrients.",
  "A group of parrots is called a pandemonium.",
  "Rabbits can see almost all the way around themselves without turning their heads.",
  "The blue whale, the largest animal alive, feeds almost exclusively on tiny shrimp-like krill.",
  "A group of butterflies is called a kaleidoscope.",
  "Sea otters use rocks as tools to crack open shellfish, sometimes keeping a favourite one tucked in a pouch of loose skin.",
  "A zebra's stripes are thought to help deter biting flies as much as they camouflage the animal.",
  "A group of hippos is called a bloat.",
  "Thanks to extra neck vertebrae, owls can rotate their heads about 270 degrees.",
  "An electric eel can generate a shock of up to 600 volts to stun prey.",
  "A group of giraffes is called a tower.",
  "Some octopuses can change both the colour and the texture of their skin in under a second."
];
