/* A curated set of pop-science facts, kept local so the start page has
   no network dependency and works offline. Sourced from well-established
   science (NASA, NOAA, standard biology/physics/chemistry references). */

window.SCIENCE_FACTS = [
  "A day on Venus is longer than its year — it takes 243 Earth days to spin once, but only 225 to orbit the Sun.",
  "Honey found in ancient Egyptian tombs is still edible after 3,000 years — its low moisture and acidity keep bacteria from growing.",
  "Octopuses have three hearts, and two of them stop beating when the animal swims.",
  "There are more possible ways to shuffle a deck of cards than there are atoms on Earth.",
  "Bananas are naturally slightly radioactive because of their potassium-40 content.",
  "A bolt of lightning is roughly five times hotter than the surface of the Sun.",
  "Sharks have been around longer than trees — sharks first appeared about 400 million years ago, trees around 350 million.",
  "Your stomach lining replaces itself every few days so it doesn't digest itself with its own acid.",
  "Neutron stars are so dense that a teaspoon of their material would weigh about a billion tonnes.",
  "Water can boil and freeze at the same time — it's called the triple point, and it happens at a very specific temperature and pressure.",
  "The human brain generates about 20 watts of electricity — enough to power a dim light bulb.",
  "A single cloud can weigh over a million kilograms, held aloft because its droplets are spread across a huge volume of air.",
  "Jupiter's Great Red Spot is a storm that has been raging for at least 350 years and is wider than Earth.",
  "Wombat droppings are cube-shaped, which stops them from rolling away and helps mark territory.",
  "Sound travels about four times faster in water than it does in air.",
  "There is a species of jellyfish, Turritopsis dohrnii, that can revert to an earlier stage of its life cycle and is effectively biologically immortal.",
  "Venus is the hottest planet in the solar system, even though Mercury is closer to the Sun, because of its thick carbon dioxide atmosphere.",
  "Your body sheds about 500 million skin cells every day.",
  "A group of flamingos is called a 'flamboyance.'",
  "The Eiffel Tower can grow more than 15 centimetres taller in summer as the iron expands in the heat.",
  "Glass is not a slow-flowing liquid — old windows are thicker at the bottom because of how they were manufactured, not because the glass moved.",
  "Some species of bamboo can grow up to 91 centimetres in a single day.",
  "The average adult human body contains enough carbon to fill about 9,000 pencils.",
  "Saturn's moon Enceladus shoots geysers of water vapour into space from an ocean hidden beneath its icy crust.",
  "A single bolt of lightning contains enough energy to toast about 100,000 slices of bread.",
  "Tardigrades ('water bears') can survive the vacuum of space, extreme radiation, and being frozen to near absolute zero.",
  "Mount Everest's summit was once at the bottom of the sea — marine fossils have been found near its peak.",
  "The DNA in a single human cell, if uncoiled, would stretch about two metres.",
  "A hummingbird's heart can beat over 1,200 times per minute during flight.",
  "Antarctica is the largest desert in the world, not the Sahara — it's classified as a desert by rainfall, not temperature.",
  "There is more computing power in a modern smartphone than was used to guide the Apollo missions to the Moon.",
  "Cows have best friends and can become stressed when separated from them.",
  "The colour of a star reveals its temperature — blue stars are hotter than red ones.",
  "It would take a commercial jet more than 800 years to reach the nearest star beyond the Sun, Proxima Centauri.",
  "Octopuses can taste with their entire skin, especially their arms.",
  "A single teaspoon of a neutron star aside, the Sun contains 99.8% of the mass in our entire solar system.",
  "Butterflies taste with their feet.",
  "The Great Barrier Reef is the largest living structure on Earth, visible from space.",
  "Elephants are one of the few animals that can recognise themselves in a mirror.",
  "A day on Earth is very gradually getting longer — about 1.8 milliseconds per century — as the Moon's gravity slows our rotation.",
  "The human nose can distinguish over a trillion different scents.",
  "Crows can recognise individual human faces and hold onto grudges for years.",
  "Photons from the Sun's core take an estimated 100,000 years to reach the surface, but only about 8 minutes to reach Earth from there.",
  "Starfish don't have brains, yet they can regenerate entire limbs, and some can regrow a whole body from a single arm.",
  "The Amazon rainforest produces roughly 20% of the world's oxygen.",
  "Cats can't taste sweetness — they lack the taste receptor gene for it.",
  "Diamonds and pencil graphite are both made of pure carbon, just arranged differently.",
  "The blue whale's heart is roughly the size of a small car and can weigh as much as an adult human.",
  "A group of crows is called a 'murder.'",
  "Mars has the largest volcano in the solar system, Olympus Mons, roughly three times the height of Mount Everest.",
  "Human bones are about as strong as steel, gram for gram, but far lighter.",
  "The Moon is slowly drifting away from Earth at about 3.8 centimetres per year.",
  "Sea otters hold hands while sleeping so they don't drift apart in the water.",
  "There are more stars in the observable universe than grains of sand on every beach on Earth.",
  "Some metals, like caesium and gallium, can melt in your hand or a cup of warm tea.",
  "Penguins propose to their mates with a pebble in some species, such as the Gentoo penguin.",
  "The human heart beats about 100,000 times a day, pumping roughly 7,500 litres of blood.",
  "Space is completely silent because sound needs a medium like air or water to travel through.",
  "A group of owls is called a 'parliament.'",
  "Octopus blood is blue because it uses copper-based haemocyanin instead of iron-based haemoglobin to carry oxygen.",
  "The tallest mountain in the solar system relative to its planet's size isn't on Mars — Rheasilvia on the asteroid Vesta comes close to rivalling Olympus Mons.",
  "Koalas have fingerprints so similar to humans that they have occasionally confused crime scene investigators.",
  "The speed of light is about 299,792 kilometres per second — fast enough to circle the Earth roughly 7.5 times in one second.",
  "An adult human body has enough iron in it to make a small nail.",
  "The coldest natural temperature ever recorded on Earth was about -89.2°C, at Vostok Station, Antarctica.",
  "Dolphins call each other by unique signature whistles, functioning much like names.",
  "Saturn is so light relative to its size that it would float in water, if you could find a bathtub big enough.",
  "A newborn's brain roughly doubles in size in its first year of life.",
  "The Pacific Ocean is so vast that it covers more area than all of Earth's landmass combined.",
  "Slime mould, despite having no brain or nervous system, can solve mazes and optimise routes efficiently.",
  "The International Space Station orbits Earth roughly every 90 minutes, meaning its crew sees about 16 sunrises a day.",
  "Human muscles and bones lose mass in microgravity, which is why astronauts must exercise for around two hours daily in space.",
  "A single strand of spider silk is stronger than a steel strand of the same thickness.",
  "The largest known prime numbers today are found using distributed computing and have tens of millions of digits.",
  "Chameleons change colour mainly to communicate mood and temperature regulation, not just camouflage.",
  "Earth's core is almost as hot as the surface of the Sun, at around 5,400°C.",
  "The mimic octopus can impersonate the shape and behaviour of over a dozen other sea creatures to avoid predators.",
  "Lakes of liquid methane and ethane exist on Saturn's moon Titan, the only other body in the solar system known to have stable liquid on its surface.",
  "Human tooth enamel is the hardest substance in the human body.",
  "A group of pandas is called an 'embarrassment.'",
  "Because of time dilation, astronauts on the ISS age very slightly slower than people on Earth."
];
