/* Time-of-day greetings across a broad set of world languages. Kept local,
   same reasoning as facts.js/namedays.js — no external translation API, no
   network dependency. These are standard phrasebook-level greetings, not
   machine translated, and lean on a general-purpose greeting where a
   language doesn't distinguish morning/afternoon/evening/night. This is a
   broad sample, not an exhaustive list of the world's ~7,000 languages.

   pronEn / pronGr are best-effort phonetic respellings (English-style and
   Greek-letter) to help with saying the phrase aloud — not IPA-precise
   transcriptions, just a practical approximation. */

window.GREETING_LANGUAGES = [
  { english: 'French', native: 'Français', morning: 'Bonjour', afternoon: 'Bonjour', evening: 'Bonsoir', night: 'Bonne nuit',
    pronEn: { morning: 'bohn-ZHOOR', afternoon: 'bohn-ZHOOR', evening: 'bohn-SWAHR', night: 'buhn NWEE' },
    pronGr: { morning: 'μπονζούρ', afternoon: 'μπονζούρ', evening: 'μπονσουάρ', night: 'μπον νουί' } },
  { english: 'Spanish', native: 'Español', morning: 'Buenos días', afternoon: 'Buenas tardes', evening: 'Buenas tardes', night: 'Buenas noches',
    pronEn: { morning: 'BWAY-nohs DEE-ahs', afternoon: 'BWAY-nahs TAR-dess', evening: 'BWAY-nahs TAR-dess', night: 'BWAY-nahs NOH-chess' },
    pronGr: { morning: 'μπουένος ντίας', afternoon: 'μπουένας τάρδες', evening: 'μπουένας τάρδες', night: 'μπουένας νότσες' } },
  { english: 'German', native: 'Deutsch', morning: 'Guten Morgen', afternoon: 'Guten Tag', evening: 'Guten Abend', night: 'Gute Nacht',
    pronEn: { morning: 'GOO-ten MOR-gen', afternoon: 'GOO-ten TAHK', evening: 'GOO-ten AH-bent', night: 'GOO-teh NAHKHT' },
    pronGr: { morning: 'γκούτεν μόργκεν', afternoon: 'γκούτεν ταγκ', evening: 'γκούτεν άμπεντ', night: 'γκούτε νάχτ' } },
  { english: 'Italian', native: 'Italiano', morning: 'Buongiorno', afternoon: 'Buongiorno', evening: 'Buonasera', night: 'Buonanotte',
    pronEn: { morning: 'bwohn-JOR-noh', afternoon: 'bwohn-JOR-noh', evening: 'bwoh-nah-SEH-rah', night: 'bwoh-nah-NOHT-teh' },
    pronGr: { morning: 'μπουοντζόρνο', afternoon: 'μπουοντζόρνο', evening: 'μπουονασέρα', night: 'μπουονανότε' } },
  { english: 'Portuguese', native: 'Português', morning: 'Bom dia', afternoon: 'Boa tarde', evening: 'Boa noite', night: 'Boa noite',
    pronEn: { morning: 'bohn DEE-ah', afternoon: 'BOH-ah TAR-jee', evening: 'BOH-ah NOY-chee', night: 'BOH-ah NOY-chee' },
    pronGr: { morning: 'μπον ντία', afternoon: 'μπόα τάρντε', evening: 'μπόα νόιτε', night: 'μπόα νόιτε' } },
  { english: 'Dutch', native: 'Nederlands', morning: 'Goedemorgen', afternoon: 'Goedemiddag', evening: 'Goedenavond', night: 'Goedenacht',
    pronEn: { morning: 'KHOO-duh-MOR-khun', afternoon: 'KHOO-duh-MID-dahkh', evening: 'KHOO-den-AH-vont', night: 'KHOO-den-AHKHT' },
    pronGr: { morning: 'χούντε μόργκεν', afternoon: 'χούντε μίνταχ', evening: 'χούντεν άβοντ', night: 'χούντεν αχτ' } },
  { english: 'Swedish', native: 'Svenska', morning: 'God morgon', afternoon: 'God eftermiddag', evening: 'God kväll', night: 'God natt',
    pronEn: { morning: 'good MOR-ron', afternoon: 'good EF-ter-mid-dahg', evening: 'good kvel', night: 'good NAHT' },
    pronGr: { morning: 'γκουντ μόρον', afternoon: 'γκουντ έφτερμινταγκ', evening: 'γκουντ κβελ', night: 'γκουντ νατ' } },
  { english: 'Norwegian', native: 'Norsk', morning: 'God morgen', afternoon: 'God ettermiddag', evening: 'God kveld', night: 'God natt',
    pronEn: { morning: 'goo MOR-gen', afternoon: 'goo ET-ter-mid-dahg', evening: 'goo kvel', night: 'goo NAHT' },
    pronGr: { morning: 'γκου μόργκεν', afternoon: 'γκου έτερμινταγκ', evening: 'γκου κβελ', night: 'γκου νατ' } },
  { english: 'Danish', native: 'Dansk', morning: 'God morgen', afternoon: 'God eftermiddag', evening: 'God aften', night: 'God nat',
    pronEn: { morning: 'goh MO-en', afternoon: 'goh EF-ter-mid-dah', evening: 'goh AF-ten', night: 'goh NAT' },
    pronGr: { morning: 'γκο μόρεν', afternoon: 'γκο έφτερμιντα', evening: 'γκο άφτεν', night: 'γκο ναντ' } },
  { english: 'Finnish', native: 'Suomi', morning: 'Hyvää huomenta', afternoon: 'Hyvää päivää', evening: 'Hyvää iltaa', night: 'Hyvää yötä',
    pronEn: { morning: 'HEW-vaa HWOH-men-tah', afternoon: 'HEW-vaa PIGH-vaa', evening: 'HEW-vaa IL-tah', night: 'HEW-vaa YUR-tuh' },
    pronGr: { morning: 'χίβα χουόμεντα', afternoon: 'χίβα πάιβα', evening: 'χίβα ίλτα', night: 'χίβα γιέτα' } },
  { english: 'Polish', native: 'Polski', morning: 'Dzień dobry', afternoon: 'Dzień dobry', evening: 'Dobry wieczór', night: 'Dobranoc',
    pronEn: { morning: 'jen DOH-brih', afternoon: 'jen DOH-brih', evening: 'DOH-brih VYEH-choor', night: 'doh-BRAH-nots' },
    pronGr: { morning: 'τζιεν ντόμπρι', afternoon: 'τζιεν ντόμπρι', evening: 'ντόμπρι βιέτσορ', night: 'ντομπράνοτς' } },
  { english: 'Czech', native: 'Čeština', morning: 'Dobré ráno', afternoon: 'Dobrý den', evening: 'Dobrý večer', night: 'Dobrou noc',
    pronEn: { morning: 'DOH-breh RAH-noh', afternoon: 'DOH-bree den', evening: 'DOH-bree VEH-cher', night: 'DOH-broh nots' },
    pronGr: { morning: 'ντόμπρε ράνο', afternoon: 'ντόμπρι ντεν', evening: 'ντόμπρι βέτσερ', night: 'ντόμπρο νοτς' } },
  { english: 'Slovak', native: 'Slovenčina', morning: 'Dobré ráno', afternoon: 'Dobrý deň', evening: 'Dobrý večer', night: 'Dobrú noc',
    pronEn: { morning: 'DOH-breh RAH-noh', afternoon: 'DOH-bree den', evening: 'DOH-bree VEH-cher', night: 'DOH-broo nots' },
    pronGr: { morning: 'ντόμπρε ράνο', afternoon: 'ντόμπρι ντεν', evening: 'ντόμπρι βέτσερ', night: 'ντόμπρου νοτς' } },
  { english: 'Slovenian', native: 'Slovenščina', morning: 'Dobro jutro', afternoon: 'Dober dan', evening: 'Dober večer', night: 'Lahko noč',
    pronEn: { morning: 'DOH-broh YOO-troh', afternoon: 'DOH-ber dahn', evening: 'DOH-ber VEH-cher', night: 'LAHKH-koh nohch' },
    pronGr: { morning: 'ντόμπρο γιούτρο', afternoon: 'ντόμπερ νταν', evening: 'ντόμπερ βέτσερ', night: 'λάχκο νοτς' } },
  { english: 'Bulgarian', native: 'Български', morning: 'Добро утро', afternoon: 'Добър ден', evening: 'Добър вечер', night: 'Лека нощ',
    pronEn: { morning: 'doh-BROH OO-troh', afternoon: 'DOH-bur den', evening: 'DOH-bur VEH-cher', night: 'LEH-kah nosht' },
    pronGr: { morning: 'ντομπρό ούτρο', afternoon: 'ντόμπαρ ντεν', evening: 'ντόμπαρ βέτσερ', night: 'λέκα νοστ' } },
  { english: 'Serbian', native: 'Српски', morning: 'Добро јутро', afternoon: 'Добар дан', evening: 'Добро вече', night: 'Лаку ноћ',
    pronEn: { morning: 'DOH-broh YOO-troh', afternoon: 'DOH-bar dahn', evening: 'DOH-broh VEH-cheh', night: 'LAH-koo nohch' },
    pronGr: { morning: 'ντόμπρο γιούτρο', afternoon: 'ντόμπαρ νταν', evening: 'ντόμπρο βέτσε', night: 'λάκου νοτς' } },
  { english: 'Croatian', native: 'Hrvatski', morning: 'Dobro jutro', afternoon: 'Dobar dan', evening: 'Dobra večer', night: 'Laku noć',
    pronEn: { morning: 'DOH-broh YOO-troh', afternoon: 'DOH-bar dahn', evening: 'DOH-brah VEH-cher', night: 'LAH-koo nohch' },
    pronGr: { morning: 'ντόμπρο γιούτρο', afternoon: 'ντόμπαρ νταν', evening: 'ντόμπρα βέτσερ', night: 'λάκου νοτς' } },
  { english: 'Bosnian', native: 'Bosanski', morning: 'Dobro jutro', afternoon: 'Dobar dan', evening: 'Dobra večer', night: 'Laku noć',
    pronEn: { morning: 'DOH-broh YOO-troh', afternoon: 'DOH-bar dahn', evening: 'DOH-brah VEH-cher', night: 'LAH-koo nohch' },
    pronGr: { morning: 'ντόμπρο γιούτρο', afternoon: 'ντόμπαρ νταν', evening: 'ντόμπρα βέτσερ', night: 'λάκου νοτς' } },
  { english: 'Macedonian', native: 'Македонски', morning: 'Добро утро', afternoon: 'Добар ден', evening: 'Добро вечер', night: 'Добра ноќ',
    pronEn: { morning: 'DOH-broh OO-troh', afternoon: 'DOH-bar den', evening: 'DOH-broh VEH-cher', night: 'DOH-brah nokj' },
    pronGr: { morning: 'ντόμπρο ούτρο', afternoon: 'ντόμπαρ ντεν', evening: 'ντόμπρο βέτσερ', night: 'ντόμπρα νοκ' } },
  { english: 'Lithuanian', native: 'Lietuvių', morning: 'Labas rytas', afternoon: 'Laba diena', evening: 'Labas vakaras', night: 'Labanakt',
    pronEn: { morning: 'LAH-bahs REE-tahs', afternoon: 'LAH-bah dee-EH-nah', evening: 'LAH-bahs VAH-kah-rahs', night: 'lah-bah-NAHKT' },
    pronGr: { morning: 'λάμπας ρίτας', afternoon: 'λάμπα ντιένα', evening: 'λάμπας βάκαρας', night: 'λαμπανάκτ' } },
  { english: 'Latvian', native: 'Latviešu', morning: 'Labrīt', afternoon: 'Labdien', evening: 'Labvakar', night: 'Ar labu nakti',
    pronEn: { morning: 'LAHB-reet', afternoon: 'LAHB-dee-en', evening: 'LAHB-vah-kar', night: 'ar LAH-boo NAHK-tee' },
    pronGr: { morning: 'λάμπριτ', afternoon: 'λάμπντιεν', evening: 'λάμπβακαρ', night: 'αρ λάμπου νάκτι' } },
  { english: 'Estonian', native: 'Eesti', morning: 'Tere hommikust', afternoon: 'Tere päevast', evening: 'Tere õhtust', night: 'Head ööd',
    pronEn: { morning: 'TEH-reh HOM-mee-kust', afternoon: 'TEH-reh PAH-eh-vahst', evening: 'TEH-reh UHKH-toost', night: 'heh-ahd URD' },
    pronGr: { morning: 'τέρε χόμικουστ', afternoon: 'τέρε πάεβαστ', evening: 'τέρε ούχτουστ', night: 'χεάντ ερντ' } },
  { english: 'Albanian', native: 'Shqip', morning: 'Mirëmëngjes', afternoon: 'Mirëdita', evening: 'Mirëmbrëma', night: 'Natën e mirë',
    pronEn: { morning: 'mee-ruh-mun-JESS', afternoon: 'mee-ruh-DEE-tah', evening: 'mee-ruhm-BRUH-mah', night: 'NAH-ten eh MEE-ruh' },
    pronGr: { morning: 'μιρεμέντζες', afternoon: 'μιρεντίτα', evening: 'μιρεμπρέμα', night: 'νάτεν ε μίρε' } },
  { english: 'Greek', native: 'Ελληνικά', morning: 'Καλημέρα', afternoon: 'Καλημέρα', evening: 'Καλησπέρα', night: 'Καληνύχτα' },
  { english: 'Maltese', native: 'Malti', morning: 'Bonġu', afternoon: 'Bonġu', evening: 'Bonswa', night: 'Il-lejl it-tajjeb',
    pronEn: { morning: 'BON-joo', afternoon: 'BON-joo', evening: 'bon-SWAH', night: 'il-LAYL it-TAY-yeb' },
    pronGr: { morning: 'μπόντζου', afternoon: 'μπόντζου', evening: 'μποσουά', night: 'ιλ λέιλ ιτ τάγιεμπ' } },
  { english: 'Basque', native: 'Euskara', morning: 'Egun on', afternoon: 'Arratsalde on', evening: 'Arratsalde on', night: 'Gabon',
    pronEn: { morning: 'EH-goon ohn', afternoon: 'ah-raht-SAHL-deh ohn', evening: 'ah-raht-SAHL-deh ohn', night: 'gah-BOHN' },
    pronGr: { morning: 'έγκουν ον', afternoon: 'αρατσάλντε ον', evening: 'αρατσάλντε ον', night: 'γκαμπόν' } },
  { english: 'Galician', native: 'Galego', morning: 'Bos días', afternoon: 'Boas tardes', evening: 'Boas tardes', night: 'Boas noites',
    pronEn: { morning: 'bohs DEE-ahs', afternoon: 'BOH-ahs TAR-dess', evening: 'BOH-ahs TAR-dess', night: 'BOH-ahs NOY-tess' },
    pronGr: { morning: 'μπος ντίας', afternoon: 'μπόας τάρδες', evening: 'μπόας τάρδες', night: 'μπόας νόιτες' } },
  { english: 'Catalan', native: 'Català', morning: 'Bon dia', afternoon: 'Bona tarda', evening: 'Bon vespre', night: 'Bona nit',
    pronEn: { morning: 'bon DEE-ah', afternoon: 'BOH-nah TAR-dah', evening: 'bon VESS-preh', night: 'BOH-nah neet' },
    pronGr: { morning: 'μπον ντία', afternoon: 'μπόνα τάρντα', evening: 'μπον βέσπρε', night: 'μπόνα νιτ' } },
  { english: 'Luxembourgish', native: 'Lëtzebuergesch', morning: 'Gudde Moien', afternoon: 'Gudde Mëtteg', evening: 'Gudden Owend', night: 'Gutt Nuecht',
    pronEn: { morning: 'GOO-deh MOY-en', afternoon: 'GOO-deh MUH-tehg', evening: 'GOO-den OH-vent', night: 'goot NOO-ekht' },
    pronGr: { morning: 'γκούντε μόγιεν', afternoon: 'γκούντε μέτεγκ', evening: 'γκούντεν όβεντ', night: 'γκουτ νούεχτ' } },
  { english: 'Corsican', native: 'Corsu', morning: 'Bongiornu', afternoon: 'Bongiornu', evening: 'Bona sera', night: 'Bona notte',
    pronEn: { morning: 'bon-JOR-noo', afternoon: 'bon-JOR-noo', evening: 'BOH-nah SEH-rah', night: 'BOH-nah NOHT-teh' },
    pronGr: { morning: 'μποντζόρνου', afternoon: 'μποντζόρνου', evening: 'μπόνα σέρα', night: 'μπόνα νότε' } },
  { english: 'Icelandic', native: 'Íslenska', morning: 'Góðan daginn', afternoon: 'Góðan daginn', evening: 'Gott kvöld', night: 'Góða nótt',
    pronEn: { morning: 'GOH-than DIE-in', afternoon: 'GOH-than DIE-in', evening: 'goht kvurld', night: 'GOH-thah noht' },
    pronGr: { morning: 'γκόθαν ντάγιν', afternoon: 'γκόθαν ντάγιν', evening: 'γκοτ κβέρλντ', night: 'γκόθα νοτ' } },
  { english: 'Welsh', native: 'Cymraeg', morning: 'Bore da', afternoon: 'Prynhawn da', evening: 'Noswaith dda', night: 'Nos da',
    pronEn: { morning: 'BOH-reh dah', afternoon: 'prin-HOWN dah', evening: 'noss-WYTH thah', night: 'nohs dah' },
    pronGr: { morning: 'μπόρε ντα', afternoon: 'πρινχάουν ντα', evening: 'νοσουάιθ θα', night: 'νος ντα' } },
  { english: 'Irish', native: 'Gaeilge', morning: 'Maidin mhaith', afternoon: 'Tráthnóna maith', evening: 'Tráthnóna maith', night: 'Oíche mhaith',
    pronEn: { morning: 'MOD-in wah', afternoon: 'TRAH-noh-nah mah', evening: 'TRAH-noh-nah mah', night: 'EE-heh wah' },
    pronGr: { morning: 'μόντιν βα', afternoon: 'τράνονα μα', evening: 'τράνονα μα', night: 'ίχε βα' } },
  { english: 'Romanian', native: 'Română', morning: 'Bună dimineața', afternoon: 'Bună ziua', evening: 'Bună seara', night: 'Noapte bună',
    pronEn: { morning: 'BOO-nuh dee-mee-NYAH-tsah', afternoon: 'BOO-nuh ZEE-wah', evening: 'BOO-nuh SYAH-rah', night: 'NWAHP-teh BOO-nuh' },
    pronGr: { morning: 'μπούνα ντιμινιάτσα', afternoon: 'μπούνα ζίουα', evening: 'μπούνα σιάρα', night: 'νουάπτε μπούνα' } },
  { english: 'Hungarian', native: 'Magyar', morning: 'Jó reggelt', afternoon: 'Jó napot', evening: 'Jó estét', night: 'Jó éjszakát',
    pronEn: { morning: 'yoh REG-gelt', afternoon: 'yoh NAH-pot', evening: 'yoh ESH-teht', night: 'yoh AY-sah-kaht' },
    pronGr: { morning: 'γιό ρέγκελτ', afternoon: 'γιό νάποτ', evening: 'γιό έστετ', night: 'γιό αϊσάκατ' } },
  { english: 'Russian', native: 'Русский', morning: 'Доброе утро', afternoon: 'Добрый день', evening: 'Добрый вечер', night: 'Спокойной ночи',
    pronEn: { morning: 'DOH-broh-yeh OO-truh', afternoon: 'DOH-bree dyen', evening: 'DOH-bree VYEH-cher', night: 'spah-KOY-noy NOH-chee' },
    pronGr: { morning: 'ντόμπροε ούτρο', afternoon: 'ντόμπρι ντιεν', evening: 'ντόμπρι βιέτσερ', night: 'σπακόινοϊ νότσι' } },
  { english: 'Ukrainian', native: 'Українська', morning: 'Добрий ранок', afternoon: 'Добрий день', evening: 'Добрий вечір', night: 'Надобраніч',
    pronEn: { morning: 'DOH-bry RAH-nok', afternoon: 'DOH-bry den', evening: 'DOH-bry VEH-chir', night: 'nah-doh-BRAH-nich' },
    pronGr: { morning: 'ντόμπρι ράνοκ', afternoon: 'ντόμπρι ντεν', evening: 'ντόμπρι βέτσιρ', night: 'ναντομπράνιτς' } },
  { english: 'Georgian', native: 'ქართული', morning: 'დილა მშვიდობისა', afternoon: 'გამარჯობა', evening: 'საღამო მშვიდობისა', night: 'ღამე მშვიდობისა',
    pronEn: { morning: 'DEE-lah mshvee-DOH-bee-sah', afternoon: 'gah-mar-JOH-bah', evening: 'sah-GHAH-moh mshvee-DOH-bee-sah', night: 'GHAH-meh mshvee-DOH-bee-sah' },
    pronGr: { morning: 'ντίλα μσβιντόμπισα', afternoon: 'γκαμαρτζόμπα', evening: 'σαγάμο μσβιντόμπισα', night: 'γάμε μσβιντόμπισα' } },
  { english: 'Armenian', native: 'Հայերեն', morning: 'Բարի լույս', afternoon: 'Բարև ձեզ', evening: 'Բարի երեկո', night: 'Բարի գիշեր',
    pronEn: { morning: 'BAH-ree LOOYS', afternoon: 'bah-REV dzez', evening: 'BAH-ree yeh-reh-KOH', night: 'BAH-ree gee-SHER' },
    pronGr: { morning: 'μπάρι λόις', afternoon: 'μπαρέβ τζεζ', evening: 'μπάρι γιερεκό', night: 'μπάρι γκισέρ' } },
  { english: 'Turkish', native: 'Türkçe', morning: 'Günaydın', afternoon: 'İyi günler', evening: 'İyi akşamlar', night: 'İyi geceler',
    pronEn: { morning: 'gew-NIGH-duhn', afternoon: 'EE-yee gewn-LEHR', evening: 'EE-yee ahk-SHAHM-lahr', night: 'EE-yee geh-jeh-LEHR' },
    pronGr: { morning: 'γκιουνάιντιν', afternoon: 'ίγι γκιουνλέρ', evening: 'ίγι ακσάμλαρ', night: 'ίγι γκετζελέρ' } },
  { english: 'Yiddish', native: 'ייִדיש', morning: 'אַ גוטן מאָרגן', afternoon: 'אַ גוטן טאָג', evening: 'אַ גוטן אָוונט', night: 'אַ גוטע נאַכט',
    pronEn: { morning: 'ah GOOT-en MOR-gen', afternoon: 'ah GOOT-en TAWG', evening: 'ah GOOT-en OH-vent', night: 'ah GOOT-eh NAHKHT' },
    pronGr: { morning: 'α γκούτεν μόργκεν', afternoon: 'α γκούτεν τογκ', evening: 'α γκούτεν όβεντ', night: 'α γκούτε νάχτ' } },
  { english: 'Hebrew', native: 'עברית', morning: 'בוקר טוב', afternoon: 'צהריים טובים', evening: 'ערב טוב', night: 'לילה טוב',
    pronEn: { morning: 'BOH-ker tohv', afternoon: 'tsoh-hoh-RYIM toh-VEEM', evening: 'EH-rev tohv', night: 'LIGH-lah tohv' },
    pronGr: { morning: 'μπόκερ τοβ', afternoon: 'τσοχορίμ τοβίμ', evening: 'έρεβ τοβ', night: 'λάιλα τοβ' } },
  { english: 'Arabic', native: 'العربية', morning: 'صباح الخير', afternoon: 'مساء الخير', evening: 'مساء الخير', night: 'تصبح على خير',
    pronEn: { morning: 'sah-BAHH al-KHAYR', afternoon: 'mah-SAH al-KHAYR', evening: 'mah-SAH al-KHAYR', night: 'TUS-bih ah-lah KHAYR' },
    pronGr: { morning: 'σαμπάχ αλ χάιρ', afternoon: 'μασά αλ χάιρ', evening: 'μασά αλ χάιρ', night: 'τούσμπιχ αλά χάιρ' } },
  { english: 'Persian', native: 'فارسی', morning: 'صبح بخیر', afternoon: 'روز بخیر', evening: 'عصر بخیر', night: 'شب بخیر',
    pronEn: { morning: 'sohb beh-KHEYR', afternoon: 'rooz beh-KHEYR', evening: 'ahsr beh-KHEYR', night: 'shahb beh-KHEYR' },
    pronGr: { morning: 'σομπ μπεχέιρ', afternoon: 'ρουζ μπεχέιρ', evening: 'ασρ μπεχέιρ', night: 'σαμπ μπεχέιρ' } },
  { english: 'Urdu', native: 'اردو', morning: 'صبح بخیر', afternoon: 'السلام علیکم', evening: 'شام بخیر', night: 'شب بخیر',
    pronEn: { morning: 'sub-h beh-KHEYR', afternoon: 'ah-sah-LAAM ah-LAY-kum', evening: 'shaam beh-KHEYR', night: 'shahb beh-KHEYR' },
    pronGr: { morning: 'σουμπχ μπεχέιρ', afternoon: 'ασαλάμ αλέικουμ', evening: 'σαμ μπεχέιρ', night: 'σαμπ μπεχέιρ' } },
  { english: 'Hindi', native: 'हिन्दी', morning: 'सुप्रभात', afternoon: 'नमस्ते', evening: 'शुभ संध्या', night: 'शुभ रात्रि',
    pronEn: { morning: 'soo-prah-BHAHT', afternoon: 'nah-mah-STEH', evening: 'shoobh SAHN-dyah', night: 'shoobh RAH-tree' },
    pronGr: { morning: 'σουπραμπάτ', afternoon: 'ναμαστέ', evening: 'σουμπχ σάντια', night: 'σουμπχ ράτρι' } },
  { english: 'Bengali', native: 'বাংলা', morning: 'শুভ সকাল', afternoon: 'শুভ অপরাহ্ন', evening: 'শুভ সন্ধ্যা', night: 'শুভ রাত্রি',
    pronEn: { morning: 'SHOO-bhoh SHOH-kal', afternoon: 'SHOO-bhoh OH-poh-rah-no', evening: 'SHOO-bhoh SHON-dhah', night: 'SHOO-bhoh RAH-tree' },
    pronGr: { morning: 'σούμπο σόκαλ', afternoon: 'σούμπο όποραχνο', evening: 'σούμπο σόντα', night: 'σούμπο ράτρι' } },
  { english: 'Punjabi', native: 'ਪੰਜਾਬੀ', morning: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ', afternoon: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ', evening: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ', night: 'ਸ਼ੁਭ ਰਾਤ੍ਰੀ',
    pronEn: { morning: 'saht sree ah-KAAL', afternoon: 'saht sree ah-KAAL', evening: 'saht sree ah-KAAL', night: 'shoobh RAH-tree' },
    pronGr: { morning: 'σατ σρι ακάλ', afternoon: 'σατ σρι ακάλ', evening: 'σατ σρι ακάλ', night: 'σουμπχ ράτρι' } },
  { english: 'Gujarati', native: 'ગુજરાતી', morning: 'શુભ સવાર', afternoon: 'નમસ્તે', evening: 'શુભ સાંજ', night: 'શુભ રાત્રિ',
    pronEn: { morning: 'SHOO-bh sah-VAAR', afternoon: 'nah-mah-STEH', evening: 'SHOO-bh saanj', night: 'SHOO-bh RAH-tree' },
    pronGr: { morning: 'σουμπ σαβάρ', afternoon: 'ναμαστέ', evening: 'σουμπ σανζ', night: 'σουμπ ράτρι' } },
  { english: 'Marathi', native: 'मराठी', morning: 'शुभ प्रभात', afternoon: 'नमस्कार', evening: 'शुभ संध्याकाळ', night: 'शुभ रात्री',
    pronEn: { morning: 'SHOO-bh prah-BHAHT', afternoon: 'nah-mah-SKAAR', evening: 'SHOO-bh sahn-dyah-KAAL', night: 'SHOO-bh RAH-tree' },
    pronGr: { morning: 'σουμπ πραμπάτ', afternoon: 'ναμασκάρ', evening: 'σουμπ σαντιακάλ', night: 'σουμπ ράτρι' } },
  { english: 'Tamil', native: 'தமிழ்', morning: 'காலை வணக்கம்', afternoon: 'மதிய வணக்கம்', evening: 'மாலை வணக்கம்', night: 'இரவு வணக்கம்',
    pronEn: { morning: 'KAH-lai vah-NAHK-kam', afternoon: 'mah-THI-yah vah-NAHK-kam', evening: 'MAH-lai vah-NAHK-kam', night: 'ee-RAH-voo vah-NAHK-kam' },
    pronGr: { morning: 'κάλαϊ βανάκαμ', afternoon: 'ματίγια βανάκαμ', evening: 'μάλαϊ βανάκαμ', night: 'ιράβου βανάκαμ' } },
  { english: 'Telugu', native: 'తెలుగు', morning: 'శుభోదయం', afternoon: 'శుభ మధ్యాహ్నం', evening: 'శుభ సాయంత్రం', night: 'శుభ రాత్రి',
    pronEn: { morning: 'shoo-boh-dah-YAM', afternoon: 'SHOO-bha mahd-YAAH-nam', evening: 'SHOO-bha sah-YAHN-tram', night: 'SHOO-bha RAH-tree' },
    pronGr: { morning: 'σουμποντάγιαμ', afternoon: 'σούμπα ματγιάχναμ', evening: 'σούμπα σαγιάντραμ', night: 'σούμπα ράτρι' } },
  { english: 'Kannada', native: 'ಕನ್ನಡ', morning: 'ಶುಭೋದಯ', afternoon: 'ನಮಸ್ಕಾರ', evening: 'ಶುಭ ಸಂಜೆ', night: 'ಶುಭ ರಾತ್ರಿ',
    pronEn: { morning: 'shoo-BOH-dah-yah', afternoon: 'nah-mah-SKAAR', evening: 'SHOO-bha sahn-JEH', night: 'SHOO-bha RAH-tree' },
    pronGr: { morning: 'σουμπόντάγια', afternoon: 'ναμασκάρ', evening: 'σούμπα σάντζε', night: 'σούμπα ράτρι' } },
  { english: 'Malayalam', native: 'മലയാളം', morning: 'സുപ്രഭാതം', afternoon: 'നമസ്കാരം', evening: 'ശുഭ സന്ധ്യ', night: 'ശുഭ രാത്രി',
    pronEn: { morning: 'soo-prah-BHAA-tham', afternoon: 'nah-mah-SKAA-ram', evening: 'SHOO-bha SAHN-dhya', night: 'SHOO-bha RAA-tree' },
    pronGr: { morning: 'σουπραμπάθαμ', afternoon: 'ναμασκάραμ', evening: 'σούμπα σάντια', night: 'σούμπα ράτρι' } },
  { english: 'Nepali', native: 'नेपाली', morning: 'नमस्ते', afternoon: 'नमस्ते', evening: 'नमस्ते', night: 'शुभ रात्री',
    pronEn: { morning: 'nah-mah-STEH', afternoon: 'nah-mah-STEH', evening: 'nah-mah-STEH', night: 'shoobh RAH-tree' },
    pronGr: { morning: 'ναμαστέ', afternoon: 'ναμαστέ', evening: 'ναμαστέ', night: 'σουμπ ράτρι' } },
  { english: 'Sinhala', native: 'සිංහල', morning: 'සුභ උදෑසනක්', afternoon: 'සුභ දහවලක්', evening: 'සුභ සන්ධ්‍යාවක්', night: 'සුභ රාත්‍රියක්',
    pronEn: { morning: 'SOO-bha oo-DAY-sah-nahk', afternoon: 'SOO-bha dah-hah-VAH-lahk', evening: 'SOO-bha sahn-DYAH-vahk', night: 'SOO-bha RAAT-ree-yahk' },
    pronGr: { morning: 'σούμπα ουντεσανάκ', afternoon: 'σούμπα νταχαβαλάκ', evening: 'σούμπα σαντιαβάκ', night: 'σούμπα ράτριγιακ' } },
  { english: 'Japanese', native: '日本語', morning: 'おはようございます', afternoon: 'こんにちは', evening: 'こんばんは', night: 'おやすみなさい',
    pronEn: { morning: 'oh-hah-YOH goh-zai-mahs', afternoon: 'kon-nee-chee-WAH', evening: 'kon-bahn-WAH', night: 'oh-yah-soo-mee-nah-SIGH' },
    pronGr: { morning: 'οχαγιό γκοζαϊμάς', afternoon: 'κονιτσιουά', evening: 'κομπανουά', night: 'ογιασουμιναζάι' } },
  { english: 'Korean', native: '한국어', morning: '좋은 아침이에요', afternoon: '안녕하세요', evening: '좋은 저녁이에요', night: '안녕히 주무세요',
    pronEn: { morning: 'JOH-eun ah-CHIM-ee-eh-yoh', afternoon: 'ahn-NYOHNG-hah-seh-yoh', evening: 'JOH-eun jeo-NYOHK-ee-eh-yoh', night: 'ahn-NYOHNG-hee joo-moo-seh-yoh' },
    pronGr: { morning: 'τσόεουν ατσίμιεγιό', afternoon: 'αννιόνγκ χασεγιό', evening: 'τσόεουν τζονιόκιεγιό', night: 'αννιόνγκι τζουμουσεγιό' } },
  { english: 'Mandarin Chinese', native: '中文', morning: '早上好', afternoon: '下午好', evening: '晚上好', night: '晚安',
    pronEn: { morning: 'dzao-shahng HOW', afternoon: 'shyah-woo HOW', evening: 'wahn-shahng HOW', night: 'wahn AHN' },
    pronGr: { morning: 'τζάο σανγκ χάο', afternoon: 'σιά ου χάο', evening: 'ουάν σανγκ χάο', night: 'ουάν αν' } },
  { english: 'Mongolian', native: 'Монгол', morning: 'Өглөөний мэнд', afternoon: 'Өдрийн мэнд', evening: 'Оройн мэнд', night: 'Сайхан амраарай',
    pronEn: { morning: 'UG-luh-nee mend', afternoon: 'UD-rin mend', evening: 'OH-roin mend', night: 'SIGH-khan ahm-RAH-righ' },
    pronGr: { morning: 'ούγκλονι μεντ', afternoon: 'ούντριν μεντ', evening: 'όροιν μεντ', night: 'σάιχαν αμράραϊ' } },
  { english: 'Kazakh', native: 'Қазақша', morning: 'Сәлеметсіз бе', afternoon: 'Сәлеметсіз бе', evening: 'Сәлеметсіз бе', night: 'Қайырлы түн',
    pronEn: { morning: 'suh-leh-met-SEEZ beh', afternoon: 'suh-leh-met-SEEZ beh', evening: 'suh-leh-met-SEEZ beh', night: 'KIGH-uhr-luh tewn' },
    pronGr: { morning: 'σαλεμετσίζ μπε', afternoon: 'σαλεμετσίζ μπε', evening: 'σαλεμετσίζ μπε', night: 'καϊρλί τουν' } },
  { english: 'Uzbek', native: 'Oʻzbekcha', morning: 'Xayrli tong', afternoon: 'Xayrli kun', evening: 'Xayrli kech', night: 'Xayrli tun',
    pronEn: { morning: 'khai-REE-lee tong', afternoon: 'khai-REE-lee koon', evening: 'khai-REE-lee kech', night: 'khai-REE-lee toon' },
    pronGr: { morning: 'χαϊρλί τονγκ', afternoon: 'χαϊρλί κουν', evening: 'χαϊρλί κετς', night: 'χαϊρλί τουν' } },
  { english: 'Burmese', native: 'မြန်မာ', morning: 'မင်္ဂလာပါ', afternoon: 'မင်္ဂလာပါ', evening: 'မင်္ဂလာပါ', night: 'မင်္ဂလာပါ',
    pronEn: { morning: 'min-gah-lah-BAH', afternoon: 'min-gah-lah-BAH', evening: 'min-gah-lah-BAH', night: 'min-gah-lah-BAH' },
    pronGr: { morning: 'μινγκαλαμπά', afternoon: 'μινγκαλαμπά', evening: 'μινγκαλαμπά', night: 'μινγκαλαμπά' } },
  { english: 'Khmer', native: 'ខ្មែរ', morning: 'អរុណសួស្តី', afternoon: 'សួស្តី', evening: 'សួស្តី', night: 'រាត្រីសួស្តី',
    pronEn: { morning: 'ah-roon soo-oh-STAY', afternoon: 'soo-oh-STAY', evening: 'soo-oh-STAY', night: 'REE-a-tray soo-oh-STAY' },
    pronGr: { morning: 'αρούν σουοστέι', afternoon: 'σουοστέι', evening: 'σουοστέι', night: 'ριατράι σουοστέι' } },
  { english: 'Lao', native: 'ລາວ', morning: 'ສະບາຍດີ', afternoon: 'ສະບາຍດີ', evening: 'ສະບາຍດີ', night: 'ສະບາຍດີ',
    pronEn: { morning: 'sah-BAI-dee', afternoon: 'sah-BAI-dee', evening: 'sah-BAI-dee', night: 'sah-BAI-dee' },
    pronGr: { morning: 'σαμπάιντι', afternoon: 'σαμπάιντι', evening: 'σαμπάιντι', night: 'σαμπάιντι' } },
  { english: 'Thai', native: 'ภาษาไทย', morning: 'อรุณสวัสดิ์', afternoon: 'สวัสดี', evening: 'สวัสดีตอนเย็น', night: 'ราตรีสวัสดิ์',
    pronEn: { morning: 'ah-roon sah-WAT-dee', afternoon: 'sah-WAT-dee', evening: 'sah-WAT-dee tohn-YEN', night: 'rah-TREE sah-WAT' },
    pronGr: { morning: 'αρούν σαβάτντι', afternoon: 'σαβάτντι', evening: 'σαβάτντι τον γιεν', night: 'ρατρί σαβάτ' } },
  { english: 'Vietnamese', native: 'Tiếng Việt', morning: 'Chào buổi sáng', afternoon: 'Chào buổi chiều', evening: 'Chào buổi tối', night: 'Chúc ngủ ngon',
    pronEn: { morning: 'chow BOO-ee sahng', afternoon: 'chow BOO-ee chyeh-oo', evening: 'chow BOO-ee toy', night: 'chook ngoo ngon' },
    pronGr: { morning: 'τσάο μπούι σανγκ', afternoon: 'τσάο μπούι τσιέου', evening: 'τσάο μπούι τόι', night: 'τσουκ νγκου νγκον' } },
  { english: 'Indonesian', native: 'Bahasa Indonesia', morning: 'Selamat pagi', afternoon: 'Selamat siang', evening: 'Selamat malam', night: 'Selamat malam',
    pronEn: { morning: 'seh-LAH-maht PAH-gee', afternoon: 'seh-LAH-maht see-AHNG', evening: 'seh-LAH-maht MAH-lahm', night: 'seh-LAH-maht MAH-lahm' },
    pronGr: { morning: 'σελάματ πάγκι', afternoon: 'σελάματ σιάνγκ', evening: 'σελάματ μάλαμ', night: 'σελάματ μάλαμ' } },
  { english: 'Malay', native: 'Bahasa Melayu', morning: 'Selamat pagi', afternoon: 'Selamat tengah hari', evening: 'Selamat petang', night: 'Selamat malam',
    pronEn: { morning: 'seh-LAH-maht PAH-gee', afternoon: 'seh-LAH-maht TUNG-ah HAH-ree', evening: 'seh-LAH-maht PEH-tahng', night: 'seh-LAH-maht MAH-lahm' },
    pronGr: { morning: 'σελάματ πάγκι', afternoon: 'σελάματ τένγκα χάρι', evening: 'σελάματ πετάνγκ', night: 'σελάματ μάλαμ' } },
  { english: 'Filipino', native: 'Tagalog', morning: 'Magandang umaga', afternoon: 'Magandang hapon', evening: 'Magandang gabi', night: 'Magandang gabi',
    pronEn: { morning: 'mah-gahn-DAHNG oo-MAH-gah', afternoon: 'mah-gahn-DAHNG HAH-pon', evening: 'mah-gahn-DAHNG gah-BEE', night: 'mah-gahn-DAHNG gah-BEE' },
    pronGr: { morning: 'μαγκαντάνγκ ουμάγκα', afternoon: 'μαγκαντάνγκ χάπον', evening: 'μαγκαντάνγκ γκαμπί', night: 'μαγκαντάνγκ γκαμπί' } },
  { english: 'Swahili', native: 'Kiswahili', morning: 'Habari za asubuhi', afternoon: 'Habari za mchana', evening: 'Habari za jioni', night: 'Usiku mwema',
    pronEn: { morning: 'hah-BAH-ree zah ah-soo-BOO-hee', afternoon: 'hah-BAH-ree zah mm-CHAH-nah', evening: 'hah-BAH-ree zah jee-OH-nee', night: 'oo-SEE-koo MWEH-mah' },
    pronGr: { morning: 'χαμπάρι ζα ασουμπούχι', afternoon: 'χαμπάρι ζα μτσάνα', evening: 'χαμπάρι ζα τζιόνι', night: 'ουσίκου μβέμα' } },
  { english: 'Amharic', native: 'አማርኛ', morning: 'ሰላም', afternoon: 'ሰላም', evening: 'ሰላም', night: 'መልካም ሌሊት',
    pronEn: { morning: 'seh-LAHM', afternoon: 'seh-LAHM', evening: 'seh-LAHM', night: 'mel-KAHM leh-LEET' },
    pronGr: { morning: 'σελάμ', afternoon: 'σελάμ', evening: 'σελάμ', night: 'μελκάμ λελίτ' } },
  { english: 'Somali', native: 'Soomaali', morning: 'Subax wanaagsan', afternoon: 'Galab wanaagsan', evening: 'Fiid wanaagsan', night: 'Habeen wanaagsan',
    pronEn: { morning: 'SOO-bahkh wah-NAHG-sahn', afternoon: 'GAH-lahb wah-NAHG-sahn', evening: 'feed wah-NAHG-sahn', night: 'hah-BEEN wah-NAHG-sahn' },
    pronGr: { morning: 'σούμπαχ ουανάγκσαν', afternoon: 'γκάλαμπ ουανάγκσαν', evening: 'φιντ ουανάγκσαν', night: 'χαμπίν ουανάγκσαν' } },
  { english: 'Hausa', native: 'Hausa', morning: 'Barka da safiya', afternoon: 'Barka da rana', evening: 'Barka da yamma', night: 'Barka da dare',
    pronEn: { morning: 'BAR-kah dah sah-FEE-yah', afternoon: 'BAR-kah dah RAH-nah', evening: 'BAR-kah dah YAHM-mah', night: 'BAR-kah dah DAH-reh' },
    pronGr: { morning: 'μπάρκα ντα σαφίγια', afternoon: 'μπάρκα ντα ράνα', evening: 'μπάρκα ντα γιάμα', night: 'μπάρκα ντα ντάρε' } },
  { english: 'Yoruba', native: 'Yorùbá', morning: 'Ẹ kú àárọ̀', afternoon: 'Ẹ kú ọ̀sán', evening: 'Ẹ kú alẹ́', night: 'Ẹ kú alẹ́',
    pronEn: { morning: 'eh koo ah-ah-ROH', afternoon: 'eh koo oh-SAHN', evening: 'eh koo ah-LEH', night: 'eh koo ah-LEH' },
    pronGr: { morning: 'ε κου αάρο', afternoon: 'ε κου οσάν', evening: 'ε κου αλέ', night: 'ε κου αλέ' } },
  { english: 'Igbo', native: 'Igbo', morning: 'Ụtụtụ ọma', afternoon: 'Ehihie ọma', evening: 'Mgbede ọma', night: 'Ka chi fo',
    pronEn: { morning: 'oo-too-too OH-mah', afternoon: 'eh-hee-hee-eh OH-mah', evening: 'mm-BEH-deh OH-mah', night: 'kah chee foh' },
    pronGr: { morning: 'ουτούτου όμα', afternoon: 'εχίχιε όμα', evening: 'μπέντε όμα', night: 'κα τσι φο' } },
  { english: 'Zulu', native: 'isiZulu', morning: 'Sawubona ekuseni', afternoon: 'Sawubona emini', evening: 'Sawubona kusihlwa', night: 'Lala kahle',
    pronEn: { morning: 'sah-woo-BOH-nah eh-koo-SEH-nee', afternoon: 'sah-woo-BOH-nah eh-MEE-nee', evening: 'sah-woo-BOH-nah koo-see-HLWAH', night: 'LAH-lah KAH-hleh' },
    pronGr: { morning: 'σαουμπόνα εκουσένι', afternoon: 'σαουμπόνα εμίνι', evening: 'σαουμπόνα κουσίχλουα', night: 'λάλα κάχλε' } },
  { english: 'Xhosa', native: 'isiXhosa', morning: 'Molo', afternoon: 'Molo', evening: 'Molo', night: 'Lala kakuhle',
    pronEn: { morning: 'MOH-loh', afternoon: 'MOH-loh', evening: 'MOH-loh', night: 'LAH-lah kah-KOOH-leh' },
    pronGr: { morning: 'μόλο', afternoon: 'μόλο', evening: 'μόλο', night: 'λάλα κακούχλε' } },
  { english: 'Afrikaans', native: 'Afrikaans', morning: 'Goeie môre', afternoon: 'Goeie middag', evening: 'Goeie naand', night: 'Goeie nag',
    pronEn: { morning: 'KHOO-ee MOH-ruh', afternoon: 'KHOO-ee MID-dahkh', evening: 'KHOO-ee nahnt', night: 'KHOO-ee nahkh' },
    pronGr: { morning: 'χούι μόρε', afternoon: 'χούι μίνταχ', evening: 'χούι ναντ', night: 'χούι ναχ' } },
  { english: 'Malagasy', native: 'Malagasy', morning: 'Manao ahoana', afternoon: 'Manao ahoana', evening: 'Manao ahoana', night: 'Tsara mandry',
    pronEn: { morning: 'mah-NOW ah-OH-nah', afternoon: 'mah-NOW ah-OH-nah', evening: 'mah-NOW ah-OH-nah', night: 'TSAH-rah MAHN-dree' },
    pronGr: { morning: 'μανάο αόνα', afternoon: 'μανάο αόνα', evening: 'μανάο αόνα', night: 'τσάρα μάντρι' } },
  { english: 'Hawaiian', native: 'ʻŌlelo Hawaiʻi', morning: 'Aloha kakahiaka', afternoon: 'Aloha ʻauinalā', evening: 'Aloha ahiahi', night: 'Pō maikaʻi',
    pronEn: { morning: 'ah-LOH-hah kah-kah-hee-AH-kah', afternoon: 'ah-LOH-hah ow-ee-nah-LAH', evening: 'ah-LOH-hah ah-hee-AH-hee', night: 'poh migh-KAH-ee' },
    pronGr: { morning: 'αλόχα κακαχιάκα', afternoon: 'αλόχα αουιναλά', evening: 'αλόχα αχιάχι', night: 'πο μαϊκάι' } },
  { english: 'Māori', native: 'Te Reo Māori', morning: 'Mōrena', afternoon: 'Kia ora', evening: 'Ahiahi mārie', night: 'Pō mārie',
    pronEn: { morning: 'MAW-reh-nah', afternoon: 'kee-ah OR-rah', evening: 'ah-hee-AH-hee MAH-ree-eh', night: 'paw MAH-ree-eh' },
    pronGr: { morning: 'μόρενα', afternoon: 'κία όρα', evening: 'αχιάχι μάριε', night: 'πο μάριε' } },
  { english: 'Samoan', native: 'Gagana Sāmoa', morning: 'Talofa', afternoon: 'Talofa', evening: 'Talofa', night: 'Manuia le pō',
    pronEn: { morning: 'tah-LOH-fah', afternoon: 'tah-LOH-fah', evening: 'tah-LOH-fah', night: 'mah-NOO-ee-ah leh paw' },
    pronGr: { morning: 'ταλόφα', afternoon: 'ταλόφα', evening: 'ταλόφα', night: 'μανούια λε πο' } },
  { english: 'Tongan', native: 'Lea Fakatonga', morning: 'Mālō e lelei', afternoon: 'Mālō e lelei', evening: 'Mālō e lelei', night: 'Mālō e lelei',
    pronEn: { morning: 'MAH-loh eh leh-LAY', afternoon: 'MAH-loh eh leh-LAY', evening: 'MAH-loh eh leh-LAY', night: 'MAH-loh eh leh-LAY' },
    pronGr: { morning: 'μάλο ε λελέι', afternoon: 'μάλο ε λελέι', evening: 'μάλο ε λελέι', night: 'μάλο ε λελέι' } },
  { english: 'Fijian', native: 'Na Vosa Vakaviti', morning: 'Bula', afternoon: 'Bula', evening: 'Bula', night: 'Moce',
    pronEn: { morning: 'MBOO-lah', afternoon: 'MBOO-lah', evening: 'MBOO-lah', night: 'MOH-theh' },
    pronGr: { morning: 'μπούλα', afternoon: 'μπούλα', evening: 'μπούλα', night: 'μόθε' } },
  { english: 'Esperanto', native: 'Esperanto', morning: 'Bonan matenon', afternoon: 'Bonan posttagmezon', evening: 'Bonan vesperon', night: 'Bonan nokton',
    pronEn: { morning: 'BOH-nahn mah-TEH-non', afternoon: 'BOH-nahn post-tahg-MEH-zon', evening: 'BOH-nahn vess-PEH-ron', night: 'BOH-nahn NOK-ton' },
    pronGr: { morning: 'μπόναν ματένον', afternoon: 'μπόναν ποστταγμέζον', evening: 'μπόναν βεσπέρον', night: 'μπόναν νόκτον' } },
  { english: 'Latin', native: 'Latina', morning: 'Salve', afternoon: 'Salve', evening: 'Salve', night: 'Bona nox',
    pronEn: { morning: 'SAHL-weh', afternoon: 'SAHL-weh', evening: 'SAHL-weh', night: 'BOH-nah nohks' },
    pronGr: { morning: 'σάλβε', afternoon: 'σάλβε', evening: 'σάλβε', night: 'μπόνα νοξ' } }
];

/* A handful of pop-culture fictional/constructed languages, for fun. These
   don't have documented time-of-day greeting forms, so the same phrase is
   used for every bucket, with its real in-universe meaning as the
   "translation" rather than a literal "Good morning". Kept as a small,
   occasional surprise mixed into the same random pool. */

window.GREETING_LANGUAGES = window.GREETING_LANGUAGES.concat([
  {
    english: 'Klingon (Star Trek)', native: 'tlhIngan Hol',
    morning: 'nuqneH', afternoon: 'nuqneH', evening: 'nuqneH', night: 'nuqneH',
    translations: { morning: 'Hello (literally "what do you want?")', afternoon: 'Hello (literally "what do you want?")', evening: 'Hello (literally "what do you want?")', night: 'Hello (literally "what do you want?")' },
    pronEn: { morning: 'nook-NEKH', afternoon: 'nook-NEKH', evening: 'nook-NEKH', night: 'nook-NEKH' },
    pronGr: { morning: 'νουκ-νεχ', afternoon: 'νουκ-νεχ', evening: 'νουκ-νεχ', night: 'νουκ-νεχ' }
  },
  {
    english: 'Sindarin Elvish (Lord of the Rings)', native: 'Edhellen',
    morning: 'Mae govannen', afternoon: 'Mae govannen', evening: 'Mae govannen', night: 'Mae govannen',
    translations: { morning: 'Well met', afternoon: 'Well met', evening: 'Well met', night: 'Well met' },
    pronEn: { morning: 'my goh-VAHN-nen', afternoon: 'my goh-VAHN-nen', evening: 'my goh-VAHN-nen', night: 'my goh-VAHN-nen' },
    pronGr: { morning: 'μάι γκοβάνεν', afternoon: 'μάι γκοβάνεν', evening: 'μάι γκοβάνεν', night: 'μάι γκοβάνεν' }
  },
  {
    english: "Na'vi (Avatar)", native: "Na'vi",
    morning: 'Kaltxì', afternoon: 'Kaltxì', evening: 'Kaltxì', night: 'Kaltxì',
    translations: { morning: 'Hello', afternoon: 'Hello', evening: 'Hello', night: 'Hello' },
    pronEn: { morning: 'kal-TEE', afternoon: 'kal-TEE', evening: 'kal-TEE', night: 'kal-TEE' },
    pronGr: { morning: 'καλτί', afternoon: 'καλτί', evening: 'καλτί', night: 'καλτί' }
  },
  {
    english: 'Dothraki (Game of Thrones)', native: 'Lekh Dothraki',
    morning: "M'athchomaroon", afternoon: "M'athchomaroon", evening: "M'athchomaroon", night: "M'athchomaroon",
    translations: { morning: 'I honor you', afternoon: 'I honor you', evening: 'I honor you', night: 'I honor you' },
    pronEn: { morning: 'mahth-choh-mah-ROHN', afternoon: 'mahth-choh-mah-ROHN', evening: 'mahth-choh-mah-ROHN', night: 'mahth-choh-mah-ROHN' },
    pronGr: { morning: 'ματσομαρόν', afternoon: 'ματσομαρόν', evening: 'ματσομαρόν', night: 'ματσομαρόν' }
  },
  {
    english: 'Simlish (The Sims)', native: 'Simlish',
    morning: 'Sul sul!', afternoon: 'Sul sul!', evening: 'Sul sul!', night: 'Sul sul!',
    translations: { morning: 'Hello!', afternoon: 'Hello!', evening: 'Hello!', night: 'Hello!' },
    pronEn: { morning: 'sool sool', afternoon: 'sool sool', evening: 'sool sool', night: 'sool sool' },
    pronGr: { morning: 'σουλ σουλ', afternoon: 'σουλ σουλ', evening: 'σουλ σουλ', night: 'σουλ σουλ' }
  },
  {
    english: 'Minionese (Despicable Me)', native: 'Minionese',
    morning: 'Bello!', afternoon: 'Bello!', evening: 'Bello!', night: 'Bello!',
    translations: { morning: 'Hello! (Minionese is mostly playful gibberish, not a real structured language)', afternoon: 'Hello! (Minionese is mostly playful gibberish, not a real structured language)', evening: 'Hello! (Minionese is mostly playful gibberish, not a real structured language)', night: 'Hello! (Minionese is mostly playful gibberish, not a real structured language)' },
    pronEn: { morning: 'BEH-loh', afternoon: 'BEH-loh', evening: 'BEH-loh', night: 'BEH-loh' },
    pronGr: { morning: 'μπέλο', afternoon: 'μπέλο', evening: 'μπέλο', night: 'μπέλο' }
  }
]);
