/* "On this day" historical events, keyed by fixed calendar date "MM-DD".
   Kept local, same reasoning as facts.js/namedays.js. This is a curated
   set of well-established events, not an exhaustive 365-day almanac —
   days without an entry show a graceful fallback instead of a guess. */

window.ON_THIS_DAY = {
  '01-01': { year: 1993, text: 'Czechoslovakia peacefully splits into the Czech Republic and Slovakia.' },
  '01-05': { year: 1914, text: "Ford Motor Company introduces the $5 workday, roughly doubling wages for many workers." },
  '01-09': { year: 2007, text: 'Steve Jobs unveils the first iPhone.' },
  '01-15': { year: 2001, text: 'Wikipedia is launched.' },
  '01-20': { year: 2009, text: 'Barack Obama is inaugurated as the first Black president of the United States.' },
  '01-22': { year: 1901, text: 'Queen Victoria dies after a 63-year reign over the United Kingdom.' },
  '01-27': { year: 1945, text: 'Soviet troops liberate the Auschwitz concentration camp.' },
  '01-28': { year: 1986, text: 'The Space Shuttle Challenger disintegrates 73 seconds after launch.' },
  '02-04': { year: 2004, text: 'Facebook, then called "Thefacebook", is launched by Mark Zuckerberg.' },
  '02-11': { year: 1990, text: 'Nelson Mandela is released from prison after 27 years.' },
  '02-14': { year: 1876, text: 'Alexander Graham Bell files his patent for the telephone.' },
  '02-15': { year: 1564, text: 'Galileo Galilei is born in Pisa.' },
  '02-20': { year: 1962, text: 'John Glenn becomes the first American to orbit the Earth.' },
  '02-23': { year: 1945, text: 'U.S. Marines raise the flag on Mount Suribachi during the Battle of Iwo Jima.' },
  '03-08': { year: 1917, text: 'The February Revolution begins in Russia (Gregorian date; a key step toward the fall of the Tsar).' },
  '03-12': { year: 1989, text: 'Tim Berners-Lee submits his proposal for what becomes the World Wide Web.' },
  '03-14': { year: 1879, text: 'Albert Einstein is born in Ulm, Germany.' },
  '03-15': { year: -44, text: 'Julius Caesar is assassinated in the Roman Senate.' },
  '03-20': { year: 2003, text: 'The United States, with coalition forces, invades Iraq.' },
  '03-26': { year: 1979, text: 'Egypt and Israel sign a peace treaty at the White House.' },
  '03-30': { year: 1867, text: 'The United States agrees to purchase Alaska from Russia.' },
  '04-04': { year: 1968, text: 'Martin Luther King Jr. is assassinated in Memphis, Tennessee.' },
  '04-06': { year: 1896, text: 'The first modern Olympic Games open in Athens, Greece.' },
  '04-12': { year: 1961, text: 'Yuri Gagarin becomes the first human to travel into space.' },
  '04-14': { year: 1912, text: 'RMS Titanic strikes an iceberg in the North Atlantic.' },
  '04-15': { year: 1912, text: 'RMS Titanic sinks after striking an iceberg the previous night.' },
  '04-18': { year: 1906, text: 'A major earthquake and fire devastate San Francisco.' },
  '04-22': { year: 1970, text: 'The first Earth Day is observed.' },
  '04-28': { year: 1789, text: 'The mutiny on the Bounty takes place.' },
  '05-01': { year: 1886, text: 'Labor demonstrations across the U.S. give rise to May Day, International Workers’ Day.' },
  '05-08': { year: 1945, text: 'Victory in Europe (VE) Day marks the end of World War II in Europe.' },
  '05-14': { year: 1948, text: 'The State of Israel is declared.' },
  '05-25': { year: 1977, text: 'The original Star Wars film premieres in the United States.' },
  '05-29': { year: 1953, text: 'Edmund Hillary and Tenzing Norgay become the first climbers confirmed to reach the summit of Mount Everest.' },
  '06-05': { year: 1989, text: 'An unidentified man stands in front of a column of tanks near Tiananmen Square, becoming known as "Tank Man."' },
  '06-06': { year: 1944, text: 'D-Day: Allied forces land in Normandy, France.' },
  '06-15': { year: 1215, text: 'King John of England seals the Magna Carta at Runnymede.' },
  '06-18': { year: 1815, text: "The Battle of Waterloo ends Napoleon Bonaparte's rule as Emperor of the French." },
  '06-25': { year: 1876, text: 'The Battle of the Little Bighorn takes place.' },
  '06-28': { year: 1914, text: 'Archduke Franz Ferdinand of Austria is assassinated in Sarajevo, setting off the chain of events leading to World War I.' },
  '07-04': { year: 1776, text: 'The United States Declaration of Independence is adopted.' },
  '07-06': { year: 1885, text: 'Louis Pasteur successfully tests his rabies vaccine.' },
  '07-10': { year: 1925, text: 'The Scopes "Monkey Trial" begins in Dayton, Tennessee.' },
  '07-14': { year: 1789, text: 'The storming of the Bastille in Paris marks the start of the French Revolution.' },
  '07-16': { year: 1969, text: 'Apollo 11 launches from Kennedy Space Center on its mission to the Moon.' },
  '07-20': { year: 1969, text: 'Apollo 11 astronauts Neil Armstrong and Buzz Aldrin become the first humans to walk on the Moon.' },
  '07-28': { year: 1914, text: 'World War I begins as Austria-Hungary declares war on Serbia.' },
  '08-02': { year: 1990, text: 'Iraq invades Kuwait, precipitating the Gulf War.' },
  '08-06': { year: 1945, text: 'The United States drops an atomic bomb on Hiroshima, Japan.' },
  '08-09': { year: 1945, text: 'The United States drops a second atomic bomb, on Nagasaki, Japan.' },
  '08-15': { year: 1947, text: 'India gains independence from British rule.' },
  '08-24': { year: 79, text: 'Mount Vesuvius erupts, burying the Roman city of Pompeii.' },
  '08-28': { year: 1963, text: 'Martin Luther King Jr. delivers his "I Have a Dream" speech in Washington, D.C.' },
  '09-01': { year: 1939, text: 'Germany invades Poland, marking the start of World War II in Europe.' },
  '09-02': { year: 1945, text: 'Japan formally surrenders, bringing World War II to an end.' },
  '09-11': { year: 2001, text: 'Terrorist attacks destroy the World Trade Center towers in New York and strike the Pentagon.' },
  '09-18': { year: 1851, text: 'The first edition of The New York Times is published.' },
  '09-24': { year: 1852, text: 'Henri Giffard makes the first powered, steerable airship flight.' },
  '09-26': { year: 1983, text: 'Soviet officer Stanislav Petrov avoids a potential nuclear war by correctly identifying a false missile-launch alarm.' },
  '10-12': { year: 1492, text: "Christopher Columbus's expedition reaches the Americas." },
  '10-14': { year: 1947, text: 'Chuck Yeager becomes the first pilot to break the sound barrier in level flight.' },
  '10-24': { year: 1945, text: 'The United Nations officially comes into existence.' },
  '10-29': { year: 1929, text: 'The Wall Street Crash ("Black Tuesday") helps trigger the Great Depression.' },
  '11-04': { year: 1922, text: "Howard Carter discovers the entrance to Tutankhamun's tomb in Egypt's Valley of the Kings." },
  '11-09': { year: 1989, text: 'The Berlin Wall falls as East Germany opens its borders.' },
  '11-19': { year: 1863, text: 'Abraham Lincoln delivers the Gettysburg Address.' },
  '11-22': { year: 1963, text: 'U.S. President John F. Kennedy is assassinated in Dallas, Texas.' },
  '11-30': { year: 1874, text: 'Winston Churchill is born.' },
  '12-01': { year: 1955, text: 'Rosa Parks refuses to give up her bus seat in Montgomery, Alabama.' },
  '12-07': { year: 1941, text: 'Japan attacks the U.S. naval base at Pearl Harbor.' },
  '12-10': { year: 1901, text: 'The first Nobel Prizes are awarded in Stockholm.' },
  '12-17': { year: 1903, text: 'The Wright brothers make the first powered, controlled airplane flight at Kitty Hawk, North Carolina.' },
  '12-21': { year: 1913, text: 'The first crossword puzzle is published, in the New York World.' },
  '12-25': { year: 800, text: 'Charlemagne is crowned Holy Roman Emperor by Pope Leo III.' }
};
